#!/bin/sh
# $Id$
# Minimize a .js file and then create a .h file
# Usage: js2h inputfile outputfile

UGLIFYJS=node_modules/uglify-js/bin/uglifyjs

if [ ! -f $UGLIFYJS ]; then
    if [ ! -d node_modules ]; then
	mkdir node_modules;
    fi
    echo "$0: Installing uglify-js"
    npm install uglify-js
fi

if [ $# -ne 2 ]; then
    echo "$0: Usage: $0 inputFile outputFile"
    exit 3
fi

$UGLIFYJS --compress --output $1.min -- $1 
mv $1 $1.tmp

mv $1.min $1
xxd -i $1 | sed -e 's/unsigned //' \
		-e 's/^char /const char /' \
		-e 's/^int /const int /' > $2
mv $1.tmp $1
