#!/bin/sh
# nashornAccessorHost - a script to invoke the Nashorn Accessor Host
#
# Usage: nashornAccessorHost [-timeout timeoutInMilliseconds] compositeAccessor1.js [compositeAccessor2.js ...]
#
# Example: (cd $PTII/org/terraswarm/accessor/accessors/web/hosts; ./nashorn/nashornAccessorHost -timeout 10000 hosts/node/test/testNodeHost.js)
# See https://www.terraswarm.org/accessors/wiki/Notes/Notes
#
# This script is syntactic sugar for the Ptolemy II command.

installMessage="$0: \$PTII/bin/ptinvoke could not be found.  Perhaps you need to install Cape Code (aka Ptolemy II?) See https://www.terraswarm.org/accessors/wiki/Main/PtolemyII"
if [ -z $PTII ]; then
    echo "$0: \$PTII was not set"
    dirname=`dirname $0`
    PTII=`(cd $dirname../../../../../../..;pwd)`
fi    

if [ ! -f "$PTII/bin/ptinvoke" ]; then
    echo $installMessage
    exit 3
fi

"$PTII/bin/ptinvoke" ptolemy.actor.lib.jjs.NashornAccessorHostApplication $@
