/** Composite containing one instance of the Greeter service wrapper.
 *  The request to the service is generated by the GenerateRequest accessor
 *  and the response is displayed by the TextDisplay accessor.
 *  @authors: Ravi Akella and Edward A. Lee
 */
exports.setup = function () {
    var generateRequest = this.instantiate('generateRequest', './GenerateRequest.js');
    
    var greeter = this.instantiate('greeter','./Greeter.js');

    var textDisplay = this.instantiate('textDisplay', 'utilities/TextDisplay.js');
    textDisplay.setParameter('title', "Received gRPC result");

    this.connect(generateRequest, 'request', greeter, 'sayHello');
    this.connect(greeter, 'sayHelloResponse', textDisplay, 'input');
}
