#! /bin/sh
# Update index.json.

ls -1 [A-Z]*.js [A-Z]*.xml | sort | \
   awk 'BEGIN {print "[" }
   {
       if (NR > 1) {
           printf(",\n")
       }
       printf("    \"%s\"", $1);
   }
   END {printf("\n]\n")}' > index.json
   
   