#! /bin/sh
# Update index.json.

ls -1 [A-Z]*.js [A-Z]*.xml | sort | \
   awk 'BEGIN {print "[" }
   {for (i = 1; i <=NF; i++) {
       print "    \"" $i "\""
       }
   }
   END {print "]"}' > index.json
   
   