#! /bin/sh
# Update index.json.

find . -name "[A-Z]*.js" -o -name "[A-Z]*.xml" | egrep -v "(Icon.xml|PtDoc.xml)$" | sed 's@^\./@@' | sort | \
   awk 'BEGIN {print "[" }
   {
       if (NR > 1) {
           printf(",\n")
       }
       printf("    \"%s\"", $1);
   }
   END {printf("\n]\n")}' > index.json
   
   
